version: '3.4'

services:
  lachesis:
    image: doublesharp/fantom-lachesis:latest
    restart: always
    ports:
      - '5050:5050'
      - '5050:5050/udp'
    volumes:
      - lachesis:/root/.lachesis

volumes:
  lachesis: {}
